In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
dataset=pd.read_csv("analysis report.csv")

In [3]:
dataset


Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0     65  Female              0.7               0.1                   187   
1     62    Male             10.9               5.5                   699   
2     62    Male              7.3               4.1                   490   
3     58    Male              1.0               0.4                   182   
4     72    Male              3.9               2.0                   195   
..   ...     ...              ...               ...                   ...   
578   60    Male              0.5               0.1                   500   
579   40    Male              0.6               0.1                    98   
580   52    Male              0.8               0.2                   245   
581   31    Male              1.3               0.5                   184   
582   38    Male              1.0               0.3                   216   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                          16                          18             6.8   
1                          64                         100             7.5   
2                          60                          68             7.0   
3                          14                          20             6.8   
4                          27                          59             7.3   
..                        ...                         ...             ...   
578                        20                          34             5.9   
579                        35                          31             6.0   
580                        48                          49             6.4   
581                        29                          32             6.8   
582                        21                          24             7.3   

     Albumin  Albumin_and_Globulin_Ratio  Dataset  
0        3.3                        0.90        1  
1        3.2                        0.74        1  
2        3.3                        0.89        1  
3        3.4                        1.00        1  
4        2.4                        0.40        1  
..       ...                         ...      ...  
578      1.6                        0.37        2  
579      3.2                        1.10        1  
580      3.2                        1.00        1  
581      3.4                        1.00        1  
582      4.4                        1.50        2  

[583 rows x 11 columns]

In [4]:
type(dataset)

pandas.core.frame.DataFrame

In [5]:

dataset.describe()

Age  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
count  583.000000       583.000000        583.000000            583.000000   
mean    44.746141         3.298799          1.486106            290.576329   
std     16.189833         6.209522          2.808498            242.937989   
min      4.000000         0.400000          0.100000             63.000000   
25%     33.000000         0.800000          0.200000            175.500000   
50%     45.000000         1.000000          0.300000            208.000000   
75%     58.000000         2.600000          1.300000            298.000000   
max     90.000000        75.000000         19.700000           2110.000000   

       Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
count                583.000000                  583.000000      583.000000   
mean                  80.713551                  109.910806        6.483190   
std                  182.620356                  288.918529        1.085451   
min                   10.000000                   10.000000        2.700000   
25%                   23.000000                   25.000000        5.800000   
50%                   35.000000                   42.000000        6.600000   
75%                   60.500000                   87.000000        7.200000   
max                 2000.000000                 4929.000000        9.600000   

          Albumin  Albumin_and_Globulin_Ratio     Dataset  
count  583.000000                  579.000000  583.000000  
mean     3.141852                    0.947064    1.286449  
std      0.795519                    0.319592    0.452490  
min      0.900000                    0.300000    1.000000  
25%      2.600000                    0.700000    1.000000  
50%      3.100000                    0.930000    1.000000  
75%      3.800000                    1.100000    2.000000  
max      5.500000                    2.800000    2.000000

In [6]:
dataset.isnull().any()

Age                           False
Gender                        False
Total_Bilirubin               False
Direct_Bilirubin              False
Alkaline_Phosphotase          False
Alamine_Aminotransferase      False
Aspartate_Aminotransferase    False
Total_Protiens                False
Albumin                       False
Albumin_and_Globulin_Ratio     True
Dataset                       False
dtype: bool

In [7]:
dataset['Albumin_and_Globulin_Ratio'].fillna((dataset['Albumin_and_Globulin_Ratio'].mean()),inplace=True)

In [8]:
dataset


Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0     65  Female              0.7               0.1                   187   
1     62    Male             10.9               5.5                   699   
2     62    Male              7.3               4.1                   490   
3     58    Male              1.0               0.4                   182   
4     72    Male              3.9               2.0                   195   
..   ...     ...              ...               ...                   ...   
578   60    Male              0.5               0.1                   500   
579   40    Male              0.6               0.1                    98   
580   52    Male              0.8               0.2                   245   
581   31    Male              1.3               0.5                   184   
582   38    Male              1.0               0.3                   216   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                          16                          18             6.8   
1                          64                         100             7.5   
2                          60                          68             7.0   
3                          14                          20             6.8   
4                          27                          59             7.3   
..                        ...                         ...             ...   
578                        20                          34             5.9   
579                        35                          31             6.0   
580                        48                          49             6.4   
581                        29                          32             6.8   
582                        21                          24             7.3   

     Albumin  Albumin_and_Globulin_Ratio  Dataset  
0        3.3                        0.90        1  
1        3.2                        0.74        1  
2        3.3                        0.89        1  
3        3.4                        1.00        1  
4        2.4                        0.40        1  
..       ...                         ...      ...  
578      1.6                        0.37        2  
579      3.2                        1.10        1  
580      3.2                        1.00        1  
581      3.4                        1.00        1  
582      4.4                        1.50        2  

[583 rows x 11 columns]

In [9]:
dataset['Albumin_and_Globulin_Ratio'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...  
578    False
579    False
580    False
581    False
582    False
Name: Albumin_and_Globulin_Ratio, Length: 583, dtype: bool

In [10]:
x=dataset.iloc[:,0:10].values
x

array([[65, 'Female', 0.7, ..., 6.8, 3.3, 0.9],
       [62, 'Male', 10.9, ..., 7.5, 3.2, 0.74],
       [62, 'Male', 7.3, ..., 7.0, 3.3, 0.89],
       ...,
       [52, 'Male', 0.8, ..., 6.4, 3.2, 1.0],
       [31, 'Male', 1.3, ..., 6.8, 3.4, 1.0],
       [38, 'Male', 1.0, ..., 7.3, 4.4, 1.5]], dtype=object)

In [11]:
y=dataset.iloc[:,1].values
y

array(['Female', 'Male', 'Male', 'Male', 'Male', 'Male', 'Female',
       'Female', 'Male', 'Male', 'Male', 'Male', 'Male', 'Female', 'Male',
       'Male', 'Male', 'Male', 'Female', 'Female', 'Male', 'Male', 'Male',
       'Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Female', 'Male',
       'Male', 'Male', 'Female', 'Female', 'Male', 'Female', 'Female',
       'Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Female', 'Male',
       'Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male',
       'Male', 'Male', 'Male', 'Male', 'Female', 'Male', 'Male', 'Female',
       'Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male',
       'Male', 'Female', 'Female', 'Female', 'Male', 'Male', 'Female',
       'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male',
       'Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male',
       'Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male',
       'Male', 'Male', 'Male', 'Male', 'Female', 'Male', 'Male', 'Mal

In [12]:
x

array([[65, 'Female', 0.7, ..., 6.8, 3.3, 0.9],
       [62, 'Male', 10.9, ..., 7.5, 3.2, 0.74],
       [62, 'Male', 7.3, ..., 7.0, 3.3, 0.89],
       ...,
       [52, 'Male', 0.8, ..., 6.4, 3.2, 1.0],
       [31, 'Male', 1.3, ..., 6.8, 3.4, 1.0],
       [38, 'Male', 1.0, ..., 7.3, 4.4, 1.5]], dtype=object)

In [13]:
import sklearn

In [14]:
sklearn.__version__

'0.23.1'

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
lb=LabelEncoder()
y=lb.fit_transform(y)
y

array([0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,

In [17]:
x[:,1]=lb.fit_transform(x[:,1])
x

array([[65, 0, 0.7, ..., 6.8, 3.3, 0.9],
       [62, 1, 10.9, ..., 7.5, 3.2, 0.74],
       [62, 1, 7.3, ..., 7.0, 3.3, 0.89],
       ...,
       [52, 1, 0.8, ..., 6.4, 3.2, 1.0],
       [31, 1, 1.3, ..., 6.8, 3.4, 1.0],
       [38, 1, 1.0, ..., 7.3, 4.4, 1.5]], dtype=object)

In [18]:
dataset.head(3)

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0   65  Female              0.7               0.1                   187   
1   62    Male             10.9               5.5                   699   
2   62    Male              7.3               4.1                   490   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   

   Albumin  Albumin_and_Globulin_Ratio  Dataset  
0      3.3                        0.90        1  
1      3.2                        0.74        1  
2      3.3                        0.89        1

In [19]:
pd.get_dummies(dataset['Gender'], prefix = 'Gender').head()

Gender_Female  Gender_Male
0              1            0
1              0            1
2              0            1
3              0            1
4              0            1

In [21]:
dataset = pd.concat([dataset,pd.get_dummies(dataset['Gender'], prefix = 'Gender')], axis=1)

In [22]:
dataset

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0     65  Female              0.7               0.1                   187   
1     62    Male             10.9               5.5                   699   
2     62    Male              7.3               4.1                   490   
3     58    Male              1.0               0.4                   182   
4     72    Male              3.9               2.0                   195   
..   ...     ...              ...               ...                   ...   
578   60    Male              0.5               0.1                   500   
579   40    Male              0.6               0.1                    98   
580   52    Male              0.8               0.2                   245   
581   31    Male              1.3               0.5                   184   
582   38    Male              1.0               0.3                   216   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                          16                          18             6.8   
1                          64                         100             7.5   
2                          60                          68             7.0   
3                          14                          20             6.8   
4                          27                          59             7.3   
..                        ...                         ...             ...   
578                        20                          34             5.9   
579                        35                          31             6.0   
580                        48                          49             6.4   
581                        29                          32             6.8   
582                        21                          24             7.3   

     Albumin  Albumin_and_Globulin_Ratio  Dataset  Gender_Female  Gender_Male  
0        3.3                        0.90        1              1            0  
1        3.2                        0.74        1              0            1  
2        3.3                        0.89        1              0            1  
3        3.4                        1.00        1              0            1  
4        2.4                        0.40        1              0            1  
..       ...                         ...      ...            ...          ...  
578      1.6                        0.37        2              0            1  
579      3.2                        1.10        1              0            1  
580      3.2                        1.00        1              0            1  
581      3.4                        1.00        1              0            1  
582      4.4                        1.50        2              0            1  

[583 rows x 13 columns]

In [23]:
dataset.describe()

Age  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
count  583.000000       583.000000        583.000000            583.000000   
mean    44.746141         3.298799          1.486106            290.576329   
std     16.189833         6.209522          2.808498            242.937989   
min      4.000000         0.400000          0.100000             63.000000   
25%     33.000000         0.800000          0.200000            175.500000   
50%     45.000000         1.000000          0.300000            208.000000   
75%     58.000000         2.600000          1.300000            298.000000   
max     90.000000        75.000000         19.700000           2110.000000   

       Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
count                583.000000                  583.000000      583.000000   
mean                  80.713551                  109.910806        6.483190   
std                  182.620356                  288.918529        1.085451   
min                   10.000000                   10.000000        2.700000   
25%                   23.000000                   25.000000        5.800000   
50%                   35.000000                   42.000000        6.600000   
75%                   60.500000                   87.000000        7.200000   
max                 2000.000000                 4929.000000        9.600000   

          Albumin  Albumin_and_Globulin_Ratio     Dataset  Gender_Female  \
count  583.000000                  583.000000  583.000000     583.000000   
mean     3.141852                    0.947064    1.286449       0.243568   
std      0.795519                    0.318492    0.452490       0.429603   
min      0.900000                    0.300000    1.000000       0.000000   
25%      2.600000                    0.700000    1.000000       0.000000   
50%      3.100000                    0.947064    1.000000       0.000000   
75%      3.800000                    1.100000    2.000000       0.000000   
max      5.500000                    2.800000    2.000000       1.000000   

       Gender_Male  
count   583.000000  
mean      0.756432  
std       0.429603  
min       0.000000  
25%       1.000000  
50%       1.000000  
75%       1.000000  
max       1.000000

In [24]:
X = dataset.drop(['Gender','Dataset'], axis=1)
X.head(583)

Age  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0     65              0.7               0.1                   187   
1     62             10.9               5.5                   699   
2     62              7.3               4.1                   490   
3     58              1.0               0.4                   182   
4     72              3.9               2.0                   195   
..   ...              ...               ...                   ...   
578   60              0.5               0.1                   500   
579   40              0.6               0.1                    98   
580   52              0.8               0.2                   245   
581   31              1.3               0.5                   184   
582   38              1.0               0.3                   216   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                          16                          18             6.8   
1                          64                         100             7.5   
2                          60                          68             7.0   
3                          14                          20             6.8   
4                          27                          59             7.3   
..                        ...                         ...             ...   
578                        20                          34             5.9   
579                        35                          31             6.0   
580                        48                          49             6.4   
581                        29                          32             6.8   
582                        21                          24             7.3   

     Albumin  Albumin_and_Globulin_Ratio  Gender_Female  Gender_Male  
0        3.3                        0.90              1            0  
1        3.2                        0.74              0            1  
2        3.3                        0.89              0            1  
3        3.4                        1.00              0            1  
4        2.4                        0.40              0            1  
..       ...                         ...            ...          ...  
578      1.6                        0.37              0            1  
579      3.2                        1.10              0            1  
580      3.2                        1.00              0            1  
581      3.4                        1.00              0            1  
582      4.4                        1.50              0            1  

[583 rows x 11 columns]

In [25]:
y = dataset['Dataset']

In [26]:
y


0      1
1      1
2      1
3      1
4      1
      ..
578    2
579    1
580    1
581    1
582    2
Name: Dataset, Length: 583, dtype: int64

In [27]:
dataset_corr = X.corr()

In [28]:
dataset_corr

Age  Total_Bilirubin  Direct_Bilirubin  \
Age                         1.000000         0.011763          0.007529   
Total_Bilirubin             0.011763         1.000000          0.874618   
Direct_Bilirubin            0.007529         0.874618          1.000000   
Alkaline_Phosphotase        0.080425         0.206669          0.234939   
Alamine_Aminotransferase   -0.086883         0.214065          0.233894   
Aspartate_Aminotransferase -0.019910         0.237831          0.257544   
Total_Protiens             -0.187461        -0.008099         -0.000139   
Albumin                    -0.265924        -0.222250         -0.228531   
Albumin_and_Globulin_Ratio -0.216089        -0.206159         -0.200004   
Gender_Female              -0.056560        -0.089291         -0.100436   
Gender_Male                 0.056560         0.089291          0.100436   

                            Alkaline_Phosphotase  Alamine_Aminotransferase  \
Age                                     0.080425                 -0.086883   
Total_Bilirubin                         0.206669                  0.214065   
Direct_Bilirubin                        0.234939                  0.233894   
Alkaline_Phosphotase                    1.000000                  0.125680   
Alamine_Aminotransferase                0.125680                  1.000000   
Aspartate_Aminotransferase              0.167196                  0.791966   
Total_Protiens                         -0.028514                 -0.042518   
Albumin                                -0.165453                 -0.029742   
Albumin_and_Globulin_Ratio             -0.233960                 -0.002374   
Gender_Female                           0.027496                 -0.082332   
Gender_Male                            -0.027496                  0.082332   

                            Aspartate_Aminotransferase  Total_Protiens  \
Age                                          -0.019910       -0.187461   
Total_Bilirubin                               0.237831       -0.008099   
Direct_Bilirubin                              0.257544       -0.000139   
Alkaline_Phosphotase                          0.167196       -0.028514   
Alamine_Aminotransferase                      0.791966       -0.042518   
Aspartate_Aminotransferase                    1.000000       -0.025645   
Total_Protiens                               -0.025645        1.000000   
Albumin                                      -0.085290        0.784053   
Albumin_and_Globulin_Ratio                   -0.070024        0.233904   
Gender_Female                                -0.080336        0.089121   
Gender_Male                                   0.080336       -0.089121   

                             Albumin  Albumin_and_Globulin_Ratio  \
Age                        -0.265924                   -0.216089   
Total_Bilirubin            -0.222250                   -0.206159   
Direct_Bilirubin           -0.228531                   -0.200004   
Alkaline_Phosphotase       -0.165453                   -0.233960   
Alamine_Aminotransferase   -0.029742                   -0.002374   
Aspartate_Aminotransferase -0.085290                   -0.070024   
Total_Protiens              0.784053                    0.233904   
Albumin                     1.000000                    0.686322   
Albumin_and_Globulin_Ratio  0.686322                    1.000000   
Gender_Female               0.093799                    0.003404   
Gender_Male                -0.093799                   -0.003404   

                            Gender_Female  Gender_Male  
Age                             -0.056560     0.056560  
Total_Bilirubin                 -0.089291     0.089291  
Direct_Bilirubin                -0.100436     0.100436  
Alkaline_Phosphotase             0.027496    -0.027496  
Alamine_Aminotransferase        -0.082332     0.082332  
Aspartate_Aminotransferase      -0.080336     0.080336  
Total_Protiens                   0.089121    -0.089121  
Albumin                          

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_test,x_train,y_test,y_train=train_test_split(x,y,test_size=0.2,random_state=0)

In [31]:
x_train

array([[55, 1, 1.8, ..., 6.1, 2.7, 0.7],
       [60, 1, 8.6, ..., 7.4, 3.0, 0.6],
       [38, 1, 2.7, ..., 7.5, 4.2, 1.2],
       ...,
       [35, 1, 1.8, ..., 6.5, 3.2, 0.9],
       [27, 1, 1.0, ..., 6.8, 3.9, 1.85],
       [65, 0, 0.7, ..., 7.2, 3.5, 0.9]], dtype=object)

In [32]:
y_train

246    1
92     1
386    2
186    1
389    1
      ..
224    1
282    1
45     2
491    2
539    2
Name: Dataset, Length: 117, dtype: int64

In [33]:
x_test

array([[55, 1, 1.1, ..., 6.2, 2.9, 0.8],
       [26, 1, 1.0, ..., 7.1, 3.7, 1.0],
       [66, 0, 0.7, ..., 6.4, 3.2, 1.0],
       ...,
       [69, 0, 0.8, ..., 8.4, 4.9, 1.4],
       [60, 1, 2.3, ..., 6.6, 3.5, 1.1],
       [26, 1, 42.8, ..., 7.5, 2.6, 0.5]], dtype=object)

In [34]:
y_test

362    2
421    2
400    2
449    1
235    1
      ..
277    1
9      1
359    2
192    1
559    1
Name: Dataset, Length: 466, dtype: int64

In [35]:
from sklearn.linear_model import LogisticRegression

In [36]:
log=LogisticRegression()

In [37]:
log.fit(x_train,y_train)

LogisticRegression()

In [38]:
x_train[0]

array([55, 1, 1.8, 9.0, 272, 22, 79, 6.1, 2.7, 0.7], dtype=object)

In [39]:
import joblib
joblib.dump(log, "liver.sav")

['liver.sav']

In [40]:
ylog=log.predict(x_test)

In [41]:
ylog

array([1, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 2, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2,
       1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2,
       2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1,
       1, 2, 1, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 1, 2,
       2, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1,
       2, 1, 1, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
       1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1,
       1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1,
       2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2,
       2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2,

In [42]:
from sklearn.metrics import accuracy_score

In [43]:
accuracy_score(ylog,y_test)

0.6738197424892703

In [44]:
from sklearn.metrics import confusion_matrix

In [45]:
cmlog=confusion_matrix(y_test,ylog)

In [46]:
cmlog

array([[249,  89],
       [ 63,  65]], dtype=int64)

In [47]:
from sklearn.tree import DecisionTreeRegressor
dt=DecisionTreeRegressor()
dt.fit(x_train,y_train)

DecisionTreeRegressor()

In [48]:
y_pred=dt.predict(x_test)
y_pred

array([1., 2., 2., 1., 2., 2., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 2., 2., 2., 1., 1., 1., 2., 1., 2., 2., 2., 2., 2.,
       2., 1., 1., 2., 1., 1., 1., 2., 2., 2., 1., 2., 2., 1., 2., 1., 1.,
       2., 1., 1., 1., 2., 2., 1., 2., 1., 1., 1., 2., 1., 2., 2., 2., 2.,
       2., 2., 1., 2., 1., 1., 1., 2., 1., 1., 2., 1., 2., 1., 2., 2., 1.,
       1., 2., 2., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 2., 2.,
       1., 1., 2., 1., 1., 1., 2., 1., 2., 2., 2., 2., 2., 1., 1., 1., 2.,
       2., 1., 2., 2., 2., 1., 1., 1., 1., 2., 2., 1., 1., 2., 2., 2., 1.,
       1., 2., 2., 2., 2., 1., 1., 2., 1., 1., 2., 2., 1., 1., 1., 2., 1.,
       2., 2., 2., 2., 2., 1., 2., 2., 1., 2., 1., 1., 1., 1., 1., 2., 1.,
       2., 1., 1., 1., 1., 2., 1., 2., 1., 1., 2., 2., 2., 1., 2., 1., 1.,
       2., 1., 1., 2., 1., 1., 1., 1., 2., 1., 2., 2., 1., 1., 2., 1., 2.,
       2., 1., 2., 1., 2., 1., 1., 2., 1., 1., 1., 2., 1., 2., 1., 1., 1.,
       2., 2., 2., 2., 1.

In [49]:
y_test

362    2
421    2
400    2
449    1
235    1
      ..
277    1
9      1
359    2
192    1
559    1
Name: Dataset, Length: 466, dtype: int64

In [50]:
from sklearn.ensemble import RandomForestRegressor
Rf=RandomForestRegressor(n_estimators=10,random_state=0,n_jobs=-1)
Rf.fit(x_train,y_train)

RandomForestRegressor(n_estimators=10, n_jobs=-1, random_state=0)

In [51]:
y_pred=Rf.predict(x_test)
y_pred

array([1.2, 1.9, 1.3, 1.3, 1.5, 1.3, 1.6, 1.4, 1. , 1. , 1.1, 1.5, 1.2,
       1. , 1.1, 1.5, 1. , 1.3, 1. , 1.5, 1. , 1.6, 1.3, 1.6, 1.3, 1. ,
       1.6, 1.7, 1.5, 1.4, 1.3, 1. , 1.7, 1.6, 1.5, 1.3, 1. , 1.3, 1.1,
       1.3, 1.8, 1.3, 1.5, 1.2, 1.3, 1.5, 1.8, 1.1, 1.5, 1.3, 1.2, 1.3,
       1. , 1. , 1.1, 1.5, 1.6, 1.7, 1.6, 1.1, 1.1, 1.1, 1.3, 1.5, 1.9,
       1.2, 1.1, 1.6, 1.8, 1.8, 1.8, 1.9, 1.8, 1.8, 1.4, 1.5, 1. , 1.6,
       1.3, 1.3, 1.8, 1.2, 1.3, 1.2, 1.2, 1.8, 1.7, 1.6, 1.9, 1. , 1. ,
       1.2, 1.1, 1.4, 1.3, 1. , 1. , 1.4, 1.4, 1. , 1. , 1.5, 1. , 1. ,
       1.9, 1. , 1.7, 1.4, 1.4, 1. , 1.5, 1.8, 1.3, 1.7, 1.2, 1.8, 1. ,
       1.4, 1.6, 1.8, 1.6, 1.7, 1.6, 1.7, 1.3, 1.3, 1. , 1.3, 1.7, 1.2,
       1.1, 1.1, 1.1, 1.2, 1.3, 1.1, 1. , 1.2, 1.7, 1.6, 1.5, 1. , 1.3,
       1.7, 1. , 1.1, 1.2, 1.1, 1.3, 1.1, 1. , 1.4, 1. , 1.6, 1.3, 1.6,
       1. , 1.3, 1. , 1.6, 1.7, 1. , 1.9, 1.7, 1.6, 1. , 1. , 1.6, 1.4,
       1. , 1.3, 1. , 1. , 1.4, 1.6, 1.9, 1.5, 1.3, 1. , 1.4, 1.

In [52]:
y_test

362    2
421    2
400    2
449    1
235    1
      ..
277    1
9      1
359    2
192    1
559    1
Name: Dataset, Length: 466, dtype: int64

In [53]:
from sklearn.tree import DecisionTreeClassifier

In [54]:
dtc=DecisionTreeClassifier(criterion='entropy',random_state=0)
dtc.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [55]:
ydtc=dtc.predict(x_test)

In [56]:

ydtc

array([1, 2, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 2,
       1, 2, 2, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 2, 2, 2, 2,
       1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1,
       1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 2,
       2, 1, 1, 2, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2,
       2, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2,
       2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1,
       2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 2, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1,

In [57]:
y_test

362    2
421    2
400    2
449    1
235    1
      ..
277    1
9      1
359    2
192    1
559    1
Name: Dataset, Length: 466, dtype: int64

In [58]:
from sklearn.metrics import accuracy_score

In [59]:
accuracy_score(ydtc,y_test)

0.6351931330472103

In [60]:
from sklearn.metrics import confusion_matrix

In [61]:
cmdtc=confusion_matrix(y_test,ydtc)

In [62]:
cmdtc

array([[227, 111],
       [ 59,  69]], dtype=int64)

In [63]:
from sklearn.ensemble import RandomForestClassifier

In [64]:
rfc=RandomForestClassifier(n_estimators=100, criterion='entropy',random_state=0)

In [65]:
rfc.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [66]:
yrfc=rfc.predict(x_test)

In [67]:
yrfc

array([1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1,
       1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 2,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1,
       1, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2,
       1, 2, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1,
       2, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 2, 1,
       1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 1, 1, 1, 2, 1, 2, 1, 2, 2, 1,
       2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 2, 1, 2, 1,
       2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2,

In [68]:
from sklearn.metrics import accuracy_score

In [69]:
accuracy_score(yrfc,y_test)

0.648068669527897

In [70]:
from sklearn.metrics import confusion_matrix

In [71]:
cmfc=confusion_matrix(y_test,yrfc)

In [72]:
cmfc

array([[250,  88],
       [ 76,  52]], dtype=int64)